apiVersion: apps/v1
kind: StatefulSet
metadata:
   namespace: planetx
   name: planetx-srv
   labels:
      app: planetx-srv
spec:
  serviceName: planetx-srv
  replicas: 1
  selector:
     matchLabels:
        app: planetx-srv
  template:
     metadata:
        labels:
           app: planetx-srv
     spec:
       containers:
       - name: planetx-srv
         image: registry.shaytech.net/pxserver:latest
         ports:
            - name: web
              containerPort: 8000
         volumeMounts:
         - name: px-cred-volume
           mountPath: /usr/src/app/creds.json
           subPath: creds.json
       volumes:
       - name: px-cred-volume
         secret:
           secretName: px-creds-json
           items:
           - key: creds.json
             path: creds.json
---
apiVersion: v1
kind: Service
metadata:
  name: planetx-srv
  namespace: planetx
spec:
  ports:
    - port: 80
      targetPort: 8000  
  selector:
     app: planetx-srv
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   namespace: planetx
   name: planetx-srv-ingress
   annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
   tls:
     - hosts:
       - planetx.shaytech.net
   rules:
   - host: planetx.shaytech.net
     http:
       paths:
          - path: /
            pathType: Prefix
            backend:
               service:
                  name: planetx-srv
                  port:
                    number: 80     
